---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dev-apps
  namespace: demo
  labels:
    chart: dev-apps
spec:
  chartGitPath: dev-apps
  releaseName: flux-dev-apps
  chart:
    git: ssh://git@github.com/stakater/flux-helm-test.git
    path: charts/dev-apps
    ref: master
  values:
    xposer:
      xposer:
        exposeServiceURL: locally