apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: dev-apps
  namespace: flux
  labels:
    chart: dev-apps
spec:
  chartGitPath: dev-apps
  releaseName: flux-dev-apps
  values:
    xposer:
      xposer:
        exposeServiceURL: locally